/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import view.console.Main;
import model.Film;
import model.Cine;
import javax.swing.JOptionPane;

/**
 *
 * @author victorhidsan
 */
public class NewJFramePelicula extends javax.swing.JFrame {

    private final Cine cine = Cine.getInstance(); // Use singleton instance

    /**
     * Creates new form NewJFramePelicula
     */
    public NewJFramePelicula() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPelicula = new javax.swing.JPanel();
        guardarPelicula = new javax.swing.JButton();
        limpiarPelicula = new javax.swing.JButton();
        peliculaFieldDuracion = new javax.swing.JTextField();
        peliculaLabelDuracion = new javax.swing.JLabel();
        peliculaFieldNombre = new javax.swing.JTextField();
        peliculaLabelNombre = new javax.swing.JLabel();
        VolverAdmin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPelicula.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                panelPeliculaComponentHidden(evt);
            }
        });

        guardarPelicula.setText("Guardar");
        guardarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarPeliculaActionPerformed(evt);
            }
        });

        limpiarPelicula.setText("Limpiar");
        limpiarPelicula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarPeliculaActionPerformed(evt);
            }
        });

        peliculaFieldDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaFieldDuracionActionPerformed(evt);
            }
        });

        peliculaLabelDuracion.setText("Duracion:");

        peliculaFieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peliculaFieldNombreActionPerformed(evt);
            }
        });

        peliculaLabelNombre.setText("Nombre Pelicula:");

        VolverAdmin.setText("Volver");
        VolverAdmin.setActionCommand("");
        VolverAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPeliculaLayout = new javax.swing.GroupLayout(panelPelicula);
        panelPelicula.setLayout(panelPeliculaLayout);
        panelPeliculaLayout.setHorizontalGroup(
            panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPeliculaLayout.createSequentialGroup()
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(peliculaLabelDuracion)
                            .addComponent(peliculaLabelNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(peliculaFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(peliculaFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPeliculaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(guardarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiarPelicula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VolverAdmin)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPeliculaLayout.setVerticalGroup(
            panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPeliculaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(peliculaFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peliculaLabelNombre))
                .addGap(18, 18, 18)
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(peliculaFieldDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(peliculaLabelDuracion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(panelPeliculaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guardarPelicula)
                    .addComponent(limpiarPelicula)
                    .addComponent(VolverAdmin))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(panelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(panelPelicula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarPeliculaActionPerformed
        String title = peliculaFieldNombre.getText();
        String durationStr = peliculaFieldDuracion.getText();

        if (title.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "El nombre de la película no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (cine.isTitleUsed(title)) { // Use direct Cine instance
            JOptionPane.showMessageDialog(this, "El nombre de la película ya está en uso.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int duration = -1;
        try {
            duration = Integer.parseInt(durationStr);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Duración no válida.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (duration > 0) {
            // Create film and add to Cine
            Film film = new Film(title, duration);
            cine.setFilms(film); // Use direct Cine instance //añadido localmente
            JOptionPane.showMessageDialog(this, "Película agregada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // Clear fields
            limpiarPeliculaActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "La duración debe ser mayor a 0.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guardarPeliculaActionPerformed

    private void peliculaFieldDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaFieldDuracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaFieldDuracionActionPerformed

    private void peliculaFieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peliculaFieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peliculaFieldNombreActionPerformed

    private void panelPeliculaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelPeliculaComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_panelPeliculaComponentHidden

    private void VolverAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverAdminActionPerformed
        // Abrir la ventana NewJFrameAdmin
        NewJFrameAdmin newJFrameAdmin = new NewJFrameAdmin();
        newJFrameAdmin.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_VolverAdminActionPerformed

    private void limpiarPeliculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarPeliculaActionPerformed
       peliculaFieldNombre.setText("");
       peliculaFieldDuracion.setText("");
    }//GEN-LAST:event_limpiarPeliculaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFramePelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFramePelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFramePelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFramePelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFramePelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton VolverAdmin;
    private javax.swing.JButton guardarPelicula;
    private javax.swing.JButton limpiarPelicula;
    private javax.swing.JPanel panelPelicula;
    private javax.swing.JTextField peliculaFieldDuracion;
    private javax.swing.JTextField peliculaFieldNombre;
    private javax.swing.JLabel peliculaLabelDuracion;
    private javax.swing.JLabel peliculaLabelNombre;
    // End of variables declaration//GEN-END:variables
}
