/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import java.io.IOException;
import model.Film;
import model.Cine;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author victorhidsan
 */
public class NewJFrameVerPeliculas extends javax.swing.JFrame {
    
    private final Cine cine = Cine.getInstance(); // Use singleton instance

    /**
     * Creates new form NewJFrameVerPeliculas
     */
    public NewJFrameVerPeliculas() {
        initComponents();
        loadPeliculas();
    }

    private void loadPeliculas() {
        ArrayList<Film> films = cine.getFilms(); // Use direct Cine instance
        DefaultListModel<String> model = new DefaultListModel<>();
        
        if (films != null && !films.isEmpty()) {
            for (Film film : films) {
                model.addElement(film.getNombre() + " - " + film.getDuracion() + " min");
            }
        } else {
            model.addElement("No hay películas disponibles");
        }
        
        jListVerPeliculas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVerPeliculas = new javax.swing.JPanel();
        jScrollPaneVerPeliculas = new javax.swing.JScrollPane();
        jListVerPeliculas = new javax.swing.JList<>();
        volverAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPaneVerPeliculas.setViewportView(jListVerPeliculas);

        volverAdminButton.setText("Volver al Admin");
        volverAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVerPeliculasLayout = new javax.swing.GroupLayout(jPanelVerPeliculas);
        jPanelVerPeliculas.setLayout(jPanelVerPeliculasLayout);
        jPanelVerPeliculasLayout.setHorizontalGroup(
            jPanelVerPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneVerPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(jPanelVerPeliculasLayout.createSequentialGroup()
                        .addComponent(volverAdminButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVerPeliculasLayout.setVerticalGroup(
            jPanelVerPeliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerPeliculasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneVerPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverAdminButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelVerPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelVerPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverAdminButtonActionPerformed
        NewJFrameAdmin newJFrameAdmin = new NewJFrameAdmin();
        newJFrameAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverAdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerPeliculas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameVerPeliculas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListVerPeliculas;
    private javax.swing.JPanel jPanelVerPeliculas;
    private javax.swing.JScrollPane jScrollPaneVerPeliculas;
    private javax.swing.JButton volverAdminButton;
    // End of variables declaration//GEN-END:variables
}
