/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import java.io.IOException;

/**
 *
 * @author victorhidsan
 */
public class NewJFrameAdmin extends javax.swing.JFrame {

    // Reference to the home frame
    private static NewJFrameHome homeFrame = NewJFrameHome.newJFrameHome;

    /**
     * Creates new form NewJFrameAdmin
     */
    public NewJFrameAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        panelGeneral = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        verPeliculas = new javax.swing.JButton();
        crearSala = new javax.swing.JButton();
        crearSesion = new javax.swing.JButton();
        anadirPelicula1 = new javax.swing.JButton();
        verSalas = new javax.swing.JButton();
        verSesiones = new javax.swing.JButton();
        volverHomeBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        title.setText("Panel Admin");

        verPeliculas.setText("Ver Peliculas");
        verPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPeliculasActionPerformed(evt);
            }
        });

        crearSala.setText("Crear Sala");
        crearSala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSalaActionPerformed(evt);
            }
        });

        crearSesion.setText("Crear Sesion");
        crearSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearSesionActionPerformed(evt);
            }
        });

        anadirPelicula1.setText("Añadir Pelicula");
        anadirPelicula1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anadirPelicula1ActionPerformed(evt);
            }
        });

        verSalas.setText("Ver Salas");
        verSalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSalasActionPerformed(evt);
            }
        });

        verSesiones.setText("Ver Sesiones");
        verSesiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSesionesActionPerformed(evt);
            }
        });
        
        volverHomeBtn.setText("Volver al Home");
        volverHomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverHomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGeneralLayout = new javax.swing.GroupLayout(panelGeneral);
        panelGeneral.setLayout(panelGeneralLayout);
        panelGeneralLayout.setHorizontalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(title)
                    .addGroup(panelGeneralLayout.createSequentialGroup()
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(crearSala, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crearSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(anadirPelicula1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(verPeliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(verSesiones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.CENTER, panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(volverHomeBtn)
                .addContainerGap())
        );
        panelGeneralLayout.setVerticalGroup(
            panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addGap(18, 18, 18)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anadirPelicula1)
                    .addComponent(verPeliculas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearSala, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verSalas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(crearSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verSesiones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(volverHomeBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPeliculasActionPerformed
        NewJFrameVerPeliculas newJFrameVerPeliculas = new NewJFrameVerPeliculas();
        newJFrameVerPeliculas.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_verPeliculasActionPerformed

    private void crearSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSalaActionPerformed
        // Abrir la ventana NewJFrameSala
        NewJFrameSala newJFrameSala = new NewJFrameSala();
        newJFrameSala.setVisible(true);
        this.dispose(); // Cerrar la ventana actual
    }//GEN-LAST:event_crearSalaActionPerformed

    private void crearSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearSesionActionPerformed
        NewJFrameSesion newJFrameSesion = new NewJFrameSesion();
        newJFrameSesion.setVisible(true);
        this.dispose(); // Cerrar la ventana actual
    }//GEN-LAST:event_crearSesionActionPerformed

    private void anadirPelicula1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anadirPelicula1ActionPerformed
        // Abrir la ventana NewJFramePelicula
        NewJFramePelicula newJFramePelicula = new NewJFramePelicula();
        newJFramePelicula.setVisible(true);
        this.dispose(); // Cerrar la ventana actual
    }//GEN-LAST:event_anadirPelicula1ActionPerformed

    private void verSalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSalasActionPerformed
        NewJFrameVerSalas newJFrameVerSalas = new NewJFrameVerSalas();
        newJFrameVerSalas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verSalasActionPerformed

    private void verSesionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSesionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verSesionesActionPerformed

    private void volverHomeBtnActionPerformed(java.awt.event.ActionEvent evt) {
        // Make the home frame visible and the admin frame invisible
        homeFrame.setVisible(true);
        this.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anadirPelicula1;
    private javax.swing.JButton crearSala;
    private javax.swing.JButton crearSesion;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JPanel panelGeneral;
    private javax.swing.JLabel title;
    private javax.swing.JButton verPeliculas;
    private javax.swing.JButton verSalas;
    private javax.swing.JButton verSesiones;
    private javax.swing.JButton volverHomeBtn;
    // End of variables declaration//GEN-END:variables
}
