/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import model.Room;
import model.Cine;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author victorhidsan
 */
public class NewJFrameVerSalas extends javax.swing.JFrame {
    
    private final Cine cine = Cine.getInstance();

    /**
     * Creates new form NewJFrameVerSalas
     */
    public NewJFrameVerSalas() {
        initComponents();
        loadSalas();
    }
    
    private void loadSalas() {
        ArrayList<Room> rooms = cine.getRooms();
        DefaultListModel<String> model = new DefaultListModel<>();
        
        if (rooms != null && !rooms.isEmpty()) {
            for (Room room : rooms) {
                model.addElement("Sala " + room.getNumSala() + " - Normales: " + room.getNumAsientos() + 
                                ", VIP: " + room.getNumAsientosVip() + ", Adaptados: " + room.getNumAsientosAdaptados());
            }
        } else {
            model.addElement("No hay salas disponibles");
        }
        
        jListVerSalas.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelVerSalas = new javax.swing.JPanel();
        jScrollPaneVerSalas = new javax.swing.JScrollPane();
        jListVerSalas = new javax.swing.JList<>();
        volverAdminButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPaneVerSalas.setViewportView(jListVerSalas);

        volverAdminButton.setText("Volver al Admin");
        volverAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverAdminButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelVerSalasLayout = new javax.swing.GroupLayout(jPanelVerSalas);
        jPanelVerSalas.setLayout(jPanelVerSalasLayout);
        jPanelVerSalasLayout.setHorizontalGroup(
            jPanelVerSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerSalasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVerSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneVerSalas, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(jPanelVerSalasLayout.createSequentialGroup()
                        .addComponent(volverAdminButton)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelVerSalasLayout.setVerticalGroup(
            jPanelVerSalasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVerSalasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneVerSalas, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(volverAdminButton)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVerSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelVerSalas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverAdminButtonActionPerformed
        NewJFrameAdmin newJFrameAdmin = new NewJFrameAdmin();
        newJFrameAdmin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverAdminButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameVerSalas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameVerSalas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> jListVerSalas;
    private javax.swing.JPanel jPanelVerSalas;
    private javax.swing.JScrollPane jScrollPaneVerSalas;
    private javax.swing.JButton volverAdminButton;
    // End of variables declaration//GEN-END:variables
}
