/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import java.io.IOException;
import model.*;

/**
 *
 * @author joaquimpinsot
 */
public class NewJFrameHome extends javax.swing.JFrame {

    static Cine myCinema = Cine.getInstance(); 
    static JFrameLogIn login = new JFrameLogIn();
    static JFrameSignUp signUp = new JFrameSignUp();
    static JFrameUserView jFrameUserView = new JFrameUserView();
    static NewJFrameHome newJFrameHome = new NewJFrameHome();
    static JFrameUserHome UserHome = new JFrameUserHome();
    static NewJFrameAdmin adminFrame = new NewJFrameAdmin();
    
    /**
     * Creates new form NewJFrameHome
     */
    public NewJFrameHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CinemaNamePanel = new javax.swing.JPanel();
        CinemaNameLbl = new javax.swing.JLabel();
        BodyPanel = new javax.swing.JPanel();
        AdminPageBtn = new javax.swing.JButton();
        UserPageBtn = new javax.swing.JButton();
        selectYourViewLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        CinemaNameLbl.setFont(new java.awt.Font("Engravers MT", 0, 48)); // NOI18N
        CinemaNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CinemaNameLbl.setText("Cines Hidalgo");

        javax.swing.GroupLayout CinemaNamePanelLayout = new javax.swing.GroupLayout(CinemaNamePanel);
        CinemaNamePanel.setLayout(CinemaNamePanelLayout);
        CinemaNamePanelLayout.setHorizontalGroup(
            CinemaNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CinemaNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CinemaNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        CinemaNamePanelLayout.setVerticalGroup(
            CinemaNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CinemaNamePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CinemaNameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                .addContainerGap())
        );

        AdminPageBtn.setText("Admin");
        AdminPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminPageBtnActionPerformed(evt);
            }
        });

        UserPageBtn.setText("Users");
        UserPageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserPageBtnActionPerformed(evt);
            }
        });

        selectYourViewLbl.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        selectYourViewLbl.setText("Select your View");

        javax.swing.GroupLayout BodyPanelLayout = new javax.swing.GroupLayout(BodyPanel);
        BodyPanel.setLayout(BodyPanelLayout);
        BodyPanelLayout.setHorizontalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(UserPageBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AdminPageBtn)
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BodyPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(selectYourViewLbl)
                .addGap(166, 166, 166))
        );
        BodyPanelLayout.setVerticalGroup(
            BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BodyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(selectYourViewLbl)
                .addGap(80, 80, 80)
                .addGroup(BodyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AdminPageBtn)
                    .addComponent(UserPageBtn))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CinemaNamePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CinemaNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BodyPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AdminPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminPageBtnActionPerformed
        // Open the Admin panel frame
        adminFrame.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AdminPageBtnActionPerformed

    private void UserPageBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserPageBtnActionPerformed
        // TODO add your handling code here:
        jFrameUserView.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_UserPageBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameHome().setVisible(true);
                 
                try {
                   myCinema.syncFilms();
                }
                catch(IOException e ){
                    System.out.println("Ha ocurrido un error IOException");
                    System.out.println(e.getMessage());
                }
                catch (Exception e) {
                    System.out.println("Ha ocurrido un error inesperado");
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminPageBtn;
    private javax.swing.JPanel BodyPanel;
    private javax.swing.JLabel CinemaNameLbl;
    private javax.swing.JPanel CinemaNamePanel;
    private javax.swing.JButton UserPageBtn;
    private javax.swing.JLabel selectYourViewLbl;

    // End of variables declaration//GEN-END:variables
}
